FROM registry.redhat.io/ubi8/ubi:8.0
MAINTAINER Dave Baker <dbaker@redhat.com>

RUN set -x && \
    ( if [ -e /etc/os-release ]; then cat /etc/os-release; fi ) && \
    dnf -y update && \
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm   && \
    dnf install -y net-tools iproute man-db \
                   nmap nmap-ncat socat openssh-clients wget 

# NOTE:
# We do *NOT* run these in this diag container since we want the yum
# data cached for future ad-hoc queries/installations/etc.
#
# ...   yum clean all && \
# ...   rm -rf /var/cache/yum
#

# Create a user by default, but we'll run as root
RUN useradd user

CMD /bin/bash

